# -*- coding: utf-8 -*-
"""Amazon Product Reviews.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BaA4L5lwIU96-Ze-Jm_XfpsqjVGYnY_d
"""

#pip install lime

#LIME
import os
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

df = pd.read_csv('/content/sample_data/Reviews.csv', encoding='latin-1')

print(df.shape)
print(df.columns)
df.head()

df = df[['Text', 'Score']]

#Clean dataset
df = df.dropna()

#Convert rating
df['label'] = df['Score'].apply(lambda x: 1 if x >= 4 else 0)

# X and Y
X = df['Text']
y = df['label']

#Train/Set
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

#TF-IDF
vectorizer = TfidfVectorizer(stop_words='english', max_features=5000)

X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

#Model LogisticRegression
model = LogisticRegression(max_iter=1000)
model.fit(X_train_vec, y_train)

#Result
y_pred = model.predict(X_test_vec)

print(classification_report(y_test, y_pred))

#Lime Function
def predict_proba(texts):
    texts = list(texts)
    X = vectorizer.transform(texts)
    return model.predict_proba(X)

from lime.lime_text import LimeTextExplainer

explainer = LimeTextExplainer(class_names=["negative", "positive"])

exp = explainer.explain_instance(
    X_test.iloc[0],
    predict_proba,
    num_features=10
)

exp.as_list()

# Visualize to Bar Chart
result = [
    ('best', 0.06880),
    ('satisfied', 0.05899),
    ('free', 0.04399),
    ('brands', 0.03734),
    ('sooner', 0.03723),
    ('Glutino', -0.02554),
    ('good',  0.02327),
    ('isn', -0.02307),
    ('texture', -0.01881),
    ('gluten', -0.01860),
]

#Seperate word and weight
words = [w for w, v in result]
values = [v for w, v in result]

#using matplotlib
import numpy as np
import matplotlib.pyplot as plt

sorted_idx = np.argsort(values)

words = np.array(words)[sorted_idx]
values = np.array(values)[sorted_idx]

plt.figure(figsize=(8,5))
plt.barh(words, values)

plt.title("LIME Explanation")
plt.xlabel("Importance")
plt.axvline(0, color='black', linewidth=1)
plt.show()

colors = ['green' if v > 0 else 'red' for v in values]

plt.barh(words, values, color=colors)

"""- Positive side:
best
satisfied
free
good
- Negative side:
gluten
Glutino
texture
isn

The bar chart visualizes word-level contributions from LIME. Positive values indicate words that support a positive sentiment prediction, while negative values indicate words that contribute to a negative sentiment prediction.
"""

#pip install shap

# word mapping (feature-> name)
import pandas as pd
import numpy as np

feature_names = vectorizer.get_feature_names_out()

shap_values_array = shap_values.values

mean_shap = np.abs(shap_values_array).mean(axis=0)

df_shap = pd.DataFrame({
    "word": feature_names,
    "importance": mean_shap
})

df_shap = df_shap.sort_values("importance", ascending=False)

print(df_shap.head(10))

#Visualize SHAP using plot
import matplotlib.pyplot as plt

top = df_shap.head(10)

plt.figure(figsize=(8,5))
plt.barh(top["word"], top["importance"])
plt.gca().invert_yaxis()
plt.title("Top SHAP Important Words")
plt.show()

import shap
import numpy as np

model = LogisticRegression(max_iter=1000)
model.fit(X_train_vec, y_train)

explainer = shap.LinearExplainer(model, X_train_vec, feature_perturbation="interventional"
)

# important for performance
X_sample = X_test_vec[:200]

shap_values = explainer(X_sample)

#Bar plot
shap.plots.bar(shap_values)

#SHAP beeswarm plot
shap.plots.beeswarm(shap_values)

"""- Bar plot
: which words matter most overall

- beeswarm plot
: distribution of word impact
positive vs negative influence


- Feature
: Review text (after conversion to TF-IDF)

- Feature meaning
: Feature = input of the model.
"""

#Waterfall plot
shap.plots.waterfall(shap_values[0])

"""equivalent to LIME but more mathematically stable"""